import Foundation
import LiteRTLM
import Combine
#if canImport(FoundationModels)
import FoundationModels
#endif
import os
/// Thin coordinator that delegates to focused sub-types.
///
/// - ModelSettings:  UserDefaults-backed settings
/// - TokenBudget:    safeMaxTokens, tokenization, token cache
/// - EngineLifecycle: engine init, retry, invalidation, memory pressure
/// - ModelDiscovery: model path resolution, listing, display names
@MainActor
final class ProviderManager: ObservableObject {
    static let shared = ProviderManager()

    // MARK: - Sub-components

    let settings = ModelSettings()
    let tokenBudget = TokenBudget()
    private lazy var lifecycle = EngineLifecycle(
        settings: settings,
        tokenBudget: tokenBudget,
        onEngineReadyChanged: { [weak self] in self?.isEngineReady = $0 },
        onEngineErrorChanged: { [weak self] in self?.engineError = $0 },
        onMemoryPressureChanged: { _ in }
    )

    // MARK: - Published State

    @Published var isEngineReady: Bool = false
    @Published var engineError: LamoError?

    // MARK: - Caches (hot paths hit these per render / per turn)

    /// Brave keychain read, cached after first load (was a Keychain query per call).
    private var braveKeyLoaded = false
    private var cachedBraveKey: String?
    /// Display-name cache (5s TTL) — was a filesystem scan per access.
    private var cachedDisplayName: (at: Date, value: String)?
    /// Provider-list cache (5s TTL) — was a framework availability query per access.
    private var cachedProviders: (at: Date, value: [ProviderType])?
    private let providerCacheTTL: TimeInterval = 5

    var braveAPIKey: String? {
        if braveKeyLoaded { return cachedBraveKey }
        let key = KeychainHelper.load(key: "brave_search_api_key")
        cachedBraveKey = key
        braveKeyLoaded = true
        return key
    }

    /// Drop cached keychain/display/provider state (e.g. after key rotation).
    func invalidateProviderCaches() {
        braveKeyLoaded = false
        cachedBraveKey = nil
        cachedDisplayName = nil
        cachedProviders = nil
    }

    var currentMaxTokens: Int? { lifecycle.currentMaxTokens }

    /// Context window that actually applies right now, per provider.
    /// LiteRT uses the dynamic KV-cache budget; Foundation Models uses the
    /// fixed system-model window (~4K). Used by the context bar so the FM
    /// fill ratio isn't computed against LiteRT's 16K-scale setting.
    var effectiveContextLimit: Int {
        if selectedProviderType == .foundationModels {
#if canImport(FoundationModels)
            return FoundationModelsProvider.contextWindowTokens
#else
            return 4096
#endif
        }
        return currentMaxTokens ?? maxNumTokens
    }

    @Published var lastToolTokens: Int = 0
    @Published var lastToolCount: Int = 0
    /// Total tool definitions (before enable/network filtering) — for "N/M tools" display.
    @Published var lastToolCountTotal: Int = ToolDefinitions.allNames.count
    /// KV-cache fill ratio at which automatic summarization triggers (0.0–1.0).
    @Published var compressionThreshold: Double = AppDefaults.compressionThreshold.wrappedValue {
        didSet { AppDefaults.compressionThreshold.wrappedValue = compressionThreshold }
    }
    /// Summary generated by the last compression. Shown in chat UI, then cleared.
    @Published var lastCompression: (oldCount: Int, summary: String)?

    // MARK: - Provider Selection

    var selectedProviderType: ProviderType {
        get { settings.providerType }
        set {
            guard settings.providerType != newValue else { return }
            settings.providerType = newValue
            invalidateEngine()
        }
    }

    var availableProviders: [ProviderType] {
        // Both providers are always listed: the deployment target (iOS 26.2+)
        // guarantees the FoundationModels framework when built with Xcode 26+,
        // and hiding the entry would also hide the *reason* (device ineligible,
        // AI disabled, model downloading) shown on the Settings screen.
        // canImport keeps builds with an older SDK safe.
        if let cache = cachedProviders,
           Date().timeIntervalSince(cache.at) < providerCacheTTL {
            return cache.value
        }
        let providers = ProviderType.allCases
        cachedProviders = (Date(), providers)
        return providers
    }

    var foundationModelsUnavailableReason: String? {
        FoundationModelsAvailability.unavailabilityReason
    }

    // MARK: - Engine accessors

    var engineForSummarization: LiteRTLM.Engine? { lifecycle.engineForSummarization }
    var currentProvider: any LLMProvider { lifecycle.currentProvider }

    // MARK: - Token Budget (forwarding)

    func tokenizeCount(_ text: String) async -> Int {
        await tokenBudget.tokenizeCount(text, engine: lifecycle.engineForSummarization)
    }

    func tokenizeMessages(_ messages: [ChatMessage]) async -> [UUID: Int] {
        await tokenBudget.tokenizeMessages(messages, engine: lifecycle.engineForSummarization)
    }

    func clearTokenCache() {
        tokenBudget.clearTokenCache()
    }

    // MARK: - Lifecycle (forwarding)

    func initializeEngineIfNeeded() async {
        await lifecycle.initializeEngineIfNeeded()
    }

    func invalidateEngine() {
        lifecycle.invalidateEngine()
    }

    func reloadEngine() {
        lifecycle.reloadEngine()
    }

    func switchModel(modelPath: String) {
        lifecycle.switchModel(modelPath: modelPath)
    }

    // MARK: - Settings (with validation + invalidation)

    var litertLMModelPath: String? {
        get { settings.litertLMModelPath }
        set {
            guard settings.litertLMModelPath != newValue else { return }
            if let newValue {
                // Filesystem validation off the MainActor (was synchronous I/O
                // in a @MainActor setter on every keystroke/selection).
                Task.detached(priority: .utility) {
                    if newValue.contains("/") {
                        if !newValue.hasSuffix(".litertlm") {
                            LamoLogger.engine.warning("Model path '\(newValue)' doesn't end in .litertlm")
                        } else if !FileManager.default.fileExists(atPath: newValue) {
                            LamoLogger.engine.warning("Model file not found at '\(newValue)'")
                        }
                    } else {
                        let fullPath = ModelDiscovery.modelsDirectory.appendingPathComponent(newValue).path
                        if !FileManager.default.fileExists(atPath: fullPath) {
                            LamoLogger.engine.warning("Model '\(newValue)' not found in models directory")
                        }
                    }
                }
            }
            settings.litertLMModelPath = newValue
            cachedDisplayName = nil
            if !lifecycle.suppressInvalidation { invalidateEngine() }
        }
    }

    var litertLMUseGPU: Bool {
        get { settings.litertLMUseGPU }
        set {
            guard settings.litertLMUseGPU != newValue else { return }
            settings.litertLMUseGPU = newValue
            invalidateEngine()
        }
    }

    var cpuThreadCount: Int {
        get { settings.cpuThreadCount }
        set {
            guard settings.cpuThreadCount != newValue else { return }
            settings.cpuThreadCount = newValue
            invalidateEngine()
        }
    }

    var topK: Int {
        get { settings.topK }
        set { settings.topK = newValue }
    }

    var topP: Double {
        get { settings.topP }
        set { settings.topP = newValue }
    }

    var temperature: Double {
        get { settings.temperature }
        set { settings.temperature = newValue }
    }

    var maxNumTokens: Int {
        get { settings.maxNumTokens }
        set {
            guard settings.maxNumTokens != newValue else { return }
            settings.maxNumTokens = newValue
            invalidateEngine()
        }
    }

    var kvCacheAuto: Bool {
        get { settings.kvCacheAuto }
        set {
            guard settings.kvCacheAuto != newValue else { return }
            // Batched defaults write (was two separate writes + invalidation
            // hazards when maxNumTokens flipped alongside the flag).
            if newValue {
                settings.setKVCache(auto: true, maxTokens: 0)
            } else if settings.maxNumTokens == 0 {
                settings.setKVCache(auto: false, maxTokens: 4096)
            } else {
                settings.kvCacheAuto = newValue
            }
            invalidateEngine()
        }
    }

    var speculativeDecoding: Bool {
        get { settings.speculativeDecoding }
        set {
            guard settings.speculativeDecoding != newValue else { return }
            settings.speculativeDecoding = newValue
            invalidateEngine()
        }
    }

    var visualTokenBudget: Int {
        get { settings.visualTokenBudget }
        set { settings.visualTokenBudget = newValue }
    }

    var systemPrompt: String {
        get { settings.systemPrompt }
        set { settings.systemPrompt = newValue }
    }

    @Published var thinkingMode: Bool = AppDefaults.thinkingMode.wrappedValue {
        didSet { settings.thinkingMode = thinkingMode }
    }

    // MARK: - Model Discovery (forwarding)

    var currentModelDisplayName: String {
        if selectedProviderType == .foundationModels {
            return String(localized: "Apple Intelligence")
        }
        let pathKey = litertLMModelPath ?? ""
        if let cache = cachedDisplayName,
           Date().timeIntervalSince(cache.at) < providerCacheTTL {
            return cache.value
        }
        let resolved = litertLMModelPath ?? ModelDiscovery.findFirstModel()
        let value = resolved.map(ModelDiscovery.displayName(forModelPath:)) ?? ""
        // Cache only when keyed on an explicit path selection; the
        // findFirstModel fallback can change as downloads complete.
        if !pathKey.isEmpty || !value.isEmpty {
            cachedDisplayName = (Date(), value)
        }
        return value
    }

    nonisolated static var modelsDirectory: URL { ModelDiscovery.modelsDirectory }
    static func displayName(forModelPath path: String) -> String { ModelDiscovery.displayName(forModelPath: path) }
    static func resolveModelPath(custom: String? = nil) -> String? { ModelDiscovery.resolveModelPath(custom: custom) }
    static func findFirstModel() -> String? { ModelDiscovery.findFirstModel() }
    static func listModels() -> [String] { ModelDiscovery.listModels() }

    func summarizeMessages(_ messages: [ChatMessage]) async -> String? {
        // Foundation Models path: summarize with the system model itself
        // (no tools, short output). Keeps auto-compression working for FM chats.
        if selectedProviderType == .foundationModels {
            return await summarizeViaFoundationModels(messages)
        }
        guard let engine = engineForSummarization, !messages.isEmpty else { return nil }

        let capped = Array(messages.suffix(20))
        let conversationText = capped.map { msg in
            let roleLabel = msg.role == .user ? "User" : "Assistant"
            return "[\(roleLabel)]: \(msg.content.prefix(500))"
        }.joined(separator: "\n\n")
        let trimmedText = String(conversationText.prefix(8_000))

        guard !trimmedText.isEmpty else { return nil }

        let summaryRequest = """
        Summarize the following conversation into a concise context block. \
        Preserve: key facts, decisions, user preferences, code, file names, and conclusions. \
        Be brief but complete — this summary replaces the original messages.

        \(trimmedText)
        """

        do {
            // Factual cool sampling — summaries must preserve facts, never
            // invent them (see GenerationGuardrails.summarizationSampling).
            // nil falls back to the engine default, same as before.
            let s = GenerationGuardrails.summarizationSampling
            let samplerConfig = try? LiteRTLM.SamplerConfig(
                topK: s.topK,
                topP: s.topP,
                temperature: s.temperature,
                seed: Int.random(in: 0..<Int(Int32.max))
            )
            let config = LiteRTLM.ConversationConfig(
                initialMessages: [LiteRTLM.Message(summaryRequest)],
                samplerConfig: samplerConfig
            )
            let summaryConv = try await engine.createConversation(with: config)
            var result = ""
            for try await chunk in summaryConv.sendMessageStream(LiteRTLM.Message("")) {
                let text = chunk.toString
                if !text.isEmpty { result += text }
            }
            return result.isEmpty ? nil : result
        } catch {
            LamoLogger.engine.warning("Conversation summarization failed: \(error)")
            return nil
        }
    }

    /// Summarization for Apple Intelligence chats — runs on the system model
    /// (no tools, capped output). iOS 26 API only (`respond(to:options:)`).
    private func summarizeViaFoundationModels(_ messages: [ChatMessage]) async -> String? {
#if canImport(FoundationModels)
        guard #available(iOS 26.0, macOS 26.0, *) else { return nil }
        guard FoundationModelsAvailability.isSupported, !messages.isEmpty else { return nil }

        let capped = Array(messages.suffix(20))
        let conversationText = capped.map { msg in
            let roleLabel = msg.role == .user ? "User" : "Assistant"
            return "[\(roleLabel)]: \(msg.content.prefix(300))"
        }.joined(separator: "\n\n")
        let trimmedText = String(conversationText.prefix(4_000))
        guard !trimmedText.isEmpty else { return nil }

        let summaryRequest = """
        Summarize the following conversation into a concise context block. \
        Preserve: key facts, decisions, user preferences, code, file names, and conclusions. \
        Be brief but complete — this summary replaces the original messages.

        \(trimmedText)
        """
        do {
            let session = LanguageModelSession(
                model: SystemLanguageModel.default,
                tools: [],
                instructions: "You are a precise summarizer. Reply with the summary only."
            )
            let options = GenerationOptions(maximumResponseTokens: 512)
            let response = try await session.respond(to: summaryRequest, options: options)
            let result = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
            return result.isEmpty ? nil : result
        } catch {
            LamoLogger.engine.warning("FM summarization failed: \(error)")
            return nil
        }
#else
        return nil
#endif
    }
}
